### ISSUE TITLE
"Something went wrong with recording the trace over your page load" error

### ISSUE THREAD

**Issue by jooj123** [paulirish/pwmetrics#166]
### Config / CLI options

```
module.exports = {
  url: 'http://localhost:3000/blahblah',
  flags: {
    runs: '2', 
    submit: false, 
    upload: false, 
    view: false, 
    expectations: true,
    chromeFlags: [
      '--headless',
    ],
  },
  expectations: {
    ttfcp: {
      warn: '>=7189',
      error: '>=9000',
    },
    ttfmp: {
      warn: '>=8387',
      error: '>=10000',
    },
    psi: {
      warn: '>=30842',
      error: '>=35000',
    },
    fv: {
      warn: '>=7190',
      error: '>=8000',
    },
    vc: {
      warn: '>=30912',
      error: '>=35000',
    },
    vc85: {
      warn: '>=28759',
      error: '>=30000',
    },
  },
};
```

### Steps to reproduce.

Run:
`pwmetrics --config=test/performance/pwmetrics-config.js`
as npm command

### Stack trace

Errors like:

Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FMP) Audit key: first-meaningful-paint

Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FMP) Audit key: estimated-input-latency

etc for each metric

### Screenshot

<img width="1062" alt="screen shot 2018-03-29 at 7 44 06 pm" src="https://user-images.githubusercontent.com/1309297/38079119-ea472a7a-3389-11e8-9b25-fc8c9fdc5efb.png">

### Environment
1. `pwmetrics` version: ~~3.1.6~~ 3.2.1
2. Chrome version: 64
3. OS version: `node:8.9.4-slim` but I can reproduce this on my mac sometimes too

This issue means I can no longer run lighthouse in my CI setup - any ideas would be greatly appreciated

**Comment by jooj123** [comment]
Updating doesnt seem to make a difference - i still get these messages

**Comment by jooj123** [comment]
I have noticed this goes away if I use the `--json` output flag.

Seems that wunderbar is causing issues (i missed the last bit of errors in original post):
" TypeError: Unexpected options.max: null. Expected number
14:54:33 [tests]     at normalizeOptions "

```
14:54:26 [tests] Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FMP) Audit key: first-meaningful-paint
14:54:26 [tests] Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FMP) Audit key: estimated-input-latency
14:54:26 [tests] Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FMP) Audit key: first-interactive
14:54:26 [tests] Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FMP) Audit key: consistently-interactive
14:54:26 [tests]   ✓ Success: Run 1 of 2 finished successfully.
14:54:26 [tests] Launching Chrome
14:54:33 [tests] Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FMP) Audit key: first-meaningful-paint
14:54:33 [tests] Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FMP) Audit key: estimated-input-latency
14:54:33 [tests] Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FMP) Audit key: first-interactive
14:54:33 [tests] Something went wrong with recording the trace over your page load. Please run Lighthouse again. (NO_FMP) Audit key: consistently-interactive
14:54:33 [tests]   ✓ Success: Run 2 of 2 finished successfully.
14:54:33 [tests]         ☆  Median run  ☆
14:54:33 [tests] TypeError: Unexpected options.max: null. Expected number
14:54:33 [tests]     at normalizeOptions (/workspace/search-results_PR-1874-head-PPB4NMFRURBGLRE3KKGPQTRTPXHLZJSJNIIQ55HIBBQO44HPZKKA/node_modules/@gribnoysup/wunderbar/lib/normalizers.js:47:11)
14:54:33 [tests]     at draw (/workspace/search-results_PR-1874-head-PPB4NMFRURBGLRE3KKGPQTRTPXHLZJSJNIIQ55HIBBQO44HPZKKA/node_modules/@gribnoysup/wunderbar/lib/index.js:62:7)
14:54:33 [tests]     at drawChart (/workspace/search-results_PR-1874-head-PPB4NMFRURBGLRE3KKGPQTRTPXHLZJSJNIIQ55HIBBQO44HPZKKA/node_modules/pwmetrics/lib/chart/chart.js:14:23)
14:54:33 [tests]     at PWMetrics.showChart (/workspace/search-results_PR-1874-head-PPB4NMFRURBGLRE3KKGPQTRTPXHLZJSJNIIQ55HIBBQO44HPZKKA/node_modules/pwmetrics/lib/index.js:232:9)
14:54:33 [tests]     at PWMetrics.displayOutput (/workspace/search-results_PR-1874-head-PPB4NMFRURBGLRE3KKGPQTRTPXHLZJSJNIIQ55HIBBQO44HPZKKA/node_modules/pwmetrics/lib/index.js:216:18)
```

**Comment by gribnoysup** [comment]
@jooj123 Can you share the output that you get with `json` flag? I assume there is `timing` missing for some metric

**Comment by jooj123** [comment]
Maybe the timing was missing - but if thats the case it should still be graceful about that and not fail with errors like: `TypeError: Unexpected options.max: null` which dont make alot of sense to devs

Its hard for me to reproduce it now, ill try again later (its a transient issue - possibly some sort of bug with lighthouse as to why it fails to generate metrics I guess)

**Comment by denar90** [comment]
@jooj123 feel free to reopen this one in case of bug reproducing)
