### ISSUE TITLE
gsheets - Error: Unable to parse range: data!A1:C1

### ISSUE THREAD

**Issue by AlahmadiQ8** [paulirish/pwmetrics#187]
I'm trying to upload to google sheets and i get the following error: 

```
The API returned an error: Error: Unable to parse range: data!A1:C1
Error: Error: Unable to parse range: data!A1:C1
    at Object.<anonymous> (/Users/mohammadmohammad/.config/yarn/global/node_modules/pwmetrics/lib/sheets/gsheets.js:86:13)
    at Generator.throw (<anonymous>)
    at rejected (/Users/mohammadmohammad/.config/yarn/global/node_modules/pwmetrics/lib/sheets/gsheets.js:17:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```
i checked https://github.com/paulirish/pwmetrics/blob/master/lib/sheets/gsheets.ts#L45 and chagned `range` to be `range: "A1:C1"` and i no longer get the error. 

I checked the [API documentation](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/append) and it looks like `range` should only accept table range format without `${options.tableName}`

**Comment by denar90** [comment]
Do you use copy of suggested google sheets example from docs?

**Comment by AlahmadiQ8** [comment]
yes. what I did is as follow: 

1 - opened [this sheet](https://docs.google.com/spreadsheets/d/14DXR9x267fOftf7sYFuUlT3djChSl6PNuPBvUD4h9Rw/edit)
2 - `cmd+a` `cmd+c` 
3 - paste in a new sheet created with my account

Looking at it again, maybe i should have clicked `file => Make copy` in the original sheet instead (i just saw that option)

**Comment by denar90** [comment]
I suppose you don't have tab called `data` or something like this.

![image](https://user-images.githubusercontent.com/6231516/44814151-73e3c400-abe4-11e8-832d-88badae52518.png)

I suggest instead try to open google sheets and go `File -> Make a copy... `
It might help.

**Comment by denar90** [comment]
@AlahmadiQ8 can we close this one?

**Comment by AlahmadiQ8** [comment]
My apologies. Yes issue indeed was fixed! Thank you for checking on this
