### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by AmitPatel-BoTreeConsulting** [paulirish/pwmetrics#41]
```
amit@amit:~$ sudo npm install --global pwmetrics
[sudo] password for amit: 
/usr/local/bin/pwmetrics -> /usr/local/lib/node_modules/pwmetrics/bin/cli.js
/usr/local/lib
`-- pwmetrics@1.2.4 
  +-- charm@1.0.2 
  | `-- inherits@2.0.3 
  +-- lighthouse@1.4.1 
  | +-- axe-core@2.1.7 
  | +-- chrome-devtools-frontend@1.0.422034 
  | +-- debug@2.6.0 
  | | `-- ms@0.7.2 
  | +-- devtools-timeline-model@1.1.6 
  | | +-- chrome-devtools-frontend@1.0.401423 
  | | `-- resolve@1.1.7 
  | +-- gl-matrix@2.3.2 
  | +-- handlebars@4.0.6 
  | | +-- async@1.5.2 
  | | +-- optimist@0.6.1 
  | | | +-- minimist@0.0.10 
  | | | `-- wordwrap@0.0.3 
  | | +-- source-map@0.4.4 
  | | | `-- amdefine@1.0.1 
  | | `-- uglify-js@2.7.5 
  | |   +-- async@0.2.10 
  | |   +-- source-map@0.5.6 
  | |   +-- uglify-to-browserify@1.0.2 
  | |   `-- yargs@3.10.0 
  | |     +-- cliui@2.1.0 
  | |     | +-- center-align@0.1.3 
  | |     | | +-- align-text@0.1.4 
  | |     | | | +-- kind-of@3.1.0 
  | |     | | | | `-- is-buffer@1.1.4 
  | |     | | | +-- longest@1.0.1 
  | |     | | | `-- repeat-string@1.6.1 
  | |     | | `-- lazy-cache@1.0.4 
  | |     | +-- right-align@0.1.3 
  | |     | `-- wordwrap@0.0.2 
  | |     `-- window-size@0.1.0 
  | +-- json-stringify-safe@5.0.1 
  | +-- marked@0.3.6 
  | +-- mkdirp@0.5.1 
  | | `-- minimist@0.0.8 
  | +-- opn@4.0.2 
  | | +-- object-assign@4.1.1 
  | | `-- pinkie-promise@2.0.1 
  | |   `-- pinkie@2.0.4 
  | +-- rimraf@2.5.4 
  | | `-- glob@7.1.1 
  | |   +-- fs.realpath@1.0.0 
  | |   +-- inflight@1.0.6 
  | |   | `-- wrappy@1.0.2 
  | |   +-- minimatch@3.0.3 
  | |   | `-- brace-expansion@1.1.6 
  | |   |   +-- balanced-match@0.4.2 
  | |   |   `-- concat-map@0.0.1 
  | |   +-- once@1.4.0 
  | |   `-- path-is-absolute@1.0.1 
  | +-- semver@5.3.0 
  | +-- speedline@1.0.3 
  | | +-- babar@0.0.3 
  | | | `-- colors@0.6.2 
  | | +-- image-ssim@0.2.0 
  | | +-- jpeg-js@0.1.2 
  | | +-- loud-rejection@1.6.0 
  | | | +-- currently-unhandled@0.4.1 
  | | | | `-- array-find-index@1.0.2 
  | | | `-- signal-exit@3.0.2 
  | | `-- meow@3.7.0 
  | |   +-- camelcase-keys@2.1.0 
  | |   | `-- camelcase@2.1.1 
  | |   +-- map-obj@1.0.1 
  | |   +-- minimist@1.2.0 
  | |   +-- normalize-package-data@2.3.5 
  | |   | +-- hosted-git-info@2.1.5 
  | |   | +-- is-builtin-module@1.0.0 
  | |   | | `-- builtin-modules@1.1.1 
  | |   | `-- validate-npm-package-license@3.0.1 
  | |   |   +-- spdx-correct@1.0.2 
  | |   |   | `-- spdx-license-ids@1.2.2 
  | |   |   `-- spdx-expression-parse@1.0.4 
  | |   +-- read-pkg-up@1.0.1 
  | |   | +-- find-up@1.1.2 
  | |   | | `-- path-exists@2.1.0 
  | |   | `-- read-pkg@1.1.0 
  | |   |   +-- load-json-file@1.1.0 
  | |   |   | +-- graceful-fs@4.1.11 
  | |   |   | +-- parse-json@2.2.0 
  | |   |   | | `-- error-ex@1.3.0 
  | |   |   | |   `-- is-arrayish@0.2.1 
  | |   |   | +-- pify@2.3.0 
  | |   |   | `-- strip-bom@2.0.0 
  | |   |   |   `-- is-utf8@0.2.1 
  | |   |   `-- path-type@1.1.0 
  | |   +-- redent@1.0.0 
  | |   | +-- indent-string@2.1.0 
  | |   | | `-- repeating@2.0.1 
  | |   | |   `-- is-finite@1.0.2 
  | |   | `-- strip-indent@1.0.1 
  | |   |   `-- get-stdin@4.0.1 
  | |   `-- trim-newlines@1.0.0 
  | +-- whatwg-url@4.3.0 
  | | +-- tr46@0.0.3 
  | | `-- webidl-conversions@3.0.1 
  | +-- ws@1.1.1 
  | | +-- options@0.0.6 
  | | `-- ultron@1.0.2 
  | `-- yargs@3.30.0 
  |   +-- camelcase@1.2.1 
  |   +-- cliui@3.2.0 
  |   | +-- string-width@1.0.2 
  |   | | +-- code-point-at@1.1.0 
  |   | | `-- is-fullwidth-code-point@1.0.0 
  |   | |   `-- number-is-nan@1.0.1 
  |   | +-- strip-ansi@3.0.1 
  |   | | `-- ansi-regex@2.1.1 
  |   | `-- wrap-ansi@2.1.0 
  |   +-- decamelize@1.2.0 
  |   +-- os-locale@1.4.0 
  |   | `-- lcid@1.0.0 
  |   |   `-- invert-kv@1.0.0 
  |   +-- window-size@0.1.4 
  |   `-- y18n@3.2.1 
  `-- median@0.0.2 

amit@amit:~$ pwmetrics http://www.shweiki.com/blog/category/business/ --runs=3
/usr/local/lib/node_modules/pwmetrics/bin/cli.js:6
const { getConfig } = require('../lib/expectations');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
amit@amit:~$ npm -v
3.8.3

```

**Comment by denar90** [comment]
Hi @AmitPatel-BoTreeConsulting . Which nodejs version are you using? `pwmetrcis` works with node >= v6.

**Comment by paulirish** [comment]
Aye. sorry @AmitPatel-BoTreeConsulting, but a more modern node version is required. Node 6 is the current LTS release so we're comfortable deprecating support for <= 5.

**Comment by AmitPatel-BoTreeConsulting** [comment]
I was using 5.x. Upgraded to the latest node(7.x) and it works now. Thanks @denar90 and @paulirish
