### ISSUE TITLE
Cannot find module 'lighthouse/lighthouse-core/config/perf.example-custom.json'

### ISSUE THREAD

**Issue by amedina** [paulirish/pwmetrics#8]
$ node --version
`v6.5.0`

$ npm --version
`3.10.3`

$ pwmetrics https://airhorner.com
```
    module.js:457
    throw err;
    ^

Error: Cannot find module 'lighthouse/lighthouse-core/config/perf.example-custom.json'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/pwmetrics/index.js:11:20)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

**Comment by samccone** [comment]
if you pull from master this is fixed :) @paulirish just needs to cut a new release
